### ISSUE TITLE
recovery: build PAC without default features

### ISSUE THREAD

**Issue by ryan-summers** [rtic-scope/cargo-rtic-scope#141]
When trying to use `rtic-scope`, the PAC lookup crate can fail with confusing errors about CC failing the link stage.

Upon analysis, I found that this is often caused by the PAC enabling default features like `device` or `rt`, which breaks linking.

It would be best to pass `default-features = false` in the PAC TOML file to ensure that no features are enabled by default, as there's no other way for the user to disable them.

**Comment by tmplt** [comment]
That is logical. Do you have a repo upon which to test changes?

**Comment by ryan-summers** [comment]
No, the only one I've tried with so far is [`stabilizer`](https://github.com/quartiq/stabilizer/issues/167). However, specifying `default-features = false` resolved the issue for my testing.
