### ISSUE TITLE
read trace clock frequency via probe-rs?

### ISSUE THREAD

**Issue by tmplt** [rtic-scope/cargo-rtic-scope#20]
Presently, the 16Mhz value is hardcoded.

**Comment by tmplt** [comment]
This is not limited to CMSIS-DAP sources. The trace clock should be read by probe-rs even if a serial source is used. Support for only using a serial source (and no CMSIS-DAP probe) is a post-v1.0.0 issue.

**Comment by tmplt** [comment]
Does it make sense to query the target for the frequency instead of waiting for the target to tell us? The query will occur after session attachment, optionally under a reset. If the target is not reset, it is in an unknown state. The read frequency is likely to differ when queried after a reset versus during an unknown state.

Functionality should nevertheless be added to easily find this frequency in firmware via `cortex-m`.

**Comment by tmplt** [comment]
@adamgreig, mind to chime in on whether it's viable to read the clock configuration from probe-rs or if there is some other approach I'm missing?

**Comment by adamgreig** [comment]
I'm not aware of any way you could figure this out in general, it depends on the chip and probe-rs's targets don't provide any information (plus even then it would depend on things like the external crystal frequency, which there's just no way to know in general).

Usually (openocd etc) the user just has to specify the frequency. If you were being cheeky I bet you could measure CYCCNT ten times in a second and round to the nearest MHz and probably be correct 9 times out of 10...

**Comment by tmplt** [comment]
I'm not well versed in clocks and their hierachies yet: is it instead viable to read the clock configuration in firmware? In case an external crystal is used a `None` could be yielded over ITM and ultimately tell the user that a frequency must be specified.

**Comment by adamgreig** [comment]
I don't think so in general, because how it's set up varies between all the different chips and HALs and so forth. You could imagine knowing how to do it for a wide range of popular microcontrollers (e.g. on an STM32F405 you could read the right RCC registers to determine if it was using an internal clock and what PLL settings, etc etc) but it's a ton of work. I don't think the HALs would store the final number anywhere in firmware, because by the time it's out the compiler it's not usually needed.

**Comment by tmplt** [comment]
Alright, `cargo-rtic-scope` will continue with an optional `--tpiu-freq` option. If not set, a `DataTraceValue` is expected over ITM containing the frequency. It's left up to the user to send the correct value.

Thanks for your input.

**Comment by tmplt** [comment]
Actually, a `--tpiu-freq` is required: if we must wait for a `DataTraceValue` we must first know the frequency to setup the `Session` in the first place. Waiting for a value over ITM is then only possible if tracing is wholly configured target-side and sourced via a serial device.
